apiVersion: v1
kind: BuildConfig
metadata:
  name: triliovault-pipeline
  labels:
    app: triliovault
    name: triliovault-pipeline
    template: application-template-triliovault-pipeline
spec:
  runPolicy: Serial
  triggers: 
    - type: "GitHub"
      github:
        secretReference:
           name: "cicd-webhook-secret"
  source: 
    git:
      uri: "https://github.com/shyam-biradar/sample-controller"
      ref: "master"
    sourceSecret:
      name: "cicd-github-clone-secret"        
  strategy:
    type: JenkinsPipeline
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
            agent any
            triggers { pollSCM('H/1 * * * *') }
            stages {
              stage('Build Stage') {
                agent { docker { image 'golang' } }
                steps {
                  sh "echo ThisisBuildStage"
                  git branch: 'master', url: 'https://github.com/shyam-biradar/sample-controller.git'
                  sh "ls -ll"
                  sh "make build"
                }
              }
              stage('Test Stage') {
                agent { docker { image 'golang' } }
                steps {
                  sh "echo ThisisTestStage"
                  sh "make test"
                }
              }
            }  
        }
  output:
  resources:
  postCommit:
